site_name: theta-client guide
site_description: RICOH THETA Web API and mobile development
site_url: https://theta360developers.github.io/theta-client-guide/
nav:
  - Home: index.md
  - Android: android.md
  - Flutter: 
      - 'Flutter Demo': 'flutter.md'
      - 'Build on Linux': 'flutter/new-project-on-linux.md'
  - React Native: 'react-native-install.md'
  - Camera Comparison: 'camera_compare.md'
  - Image Compression: 'compression.md'
  - Verify Images: 'verify_image.md'

extra:
  analytics: 
    provider: google
    property: G-M64WFDW435
theme:
  name: material
  palette:
    primary: 'light green'
    accent: 'lime'
  logo: images/icon/green-logo-192x192.png
  favicon: images/icon/favicon-16x16.png
  features:
    - content.code.copy
    - navigation.expand
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
# plugins:
#   - social

