site_name: theta-client guide
site_description: RICOH THETA Web API and mobile development
site_url: https://theta360developers.github.io/theta-client-guide/
repo_url: https://github.com/theta360developers/theta-client-guide
nav:
  - Home: index.md
  - Android: android.md
  - Flutter: 
      - 'Flutter Demo': 'flutter.md'
      - 'Build on Linux': 'flutter/new-project-on-linux.md'
  - React Native: 
      - 'React Native Install': 'react-native-install.md'
      - 'How to Install Node.js': 'how-to-install-nodejs.md'
      - 'How to Install Android Emulator': 'how-to-setup-android-emulator.md'
  - Camera Comparison: 'camera_compare.md'
  - Image Compression: 'compression.md'
  - Verify Images: 'verify_image.md'

extra:
  analytics: 
    provider: google
    property: G-M64WFDW435
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: 'light green'
      accent: 'lime'
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for light mode
    - scheme: slate
      primary: 'light green'
      accent: 'lime'
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  logo: images/icon/green-logo-192x192.png
  favicon: images/icon/favicon-16x16.png
  icon:
    edit: material/pencil-plus
  features:
    - content.code.copy
    - navigation.expand
    - content.action.edit
  custom_dir: overrides
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
edit_uri: edit/main/docs/

plugins:
  - glightbox
  - search
  # - social

